DatabaseProject/Controllers/ContentItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DatabaseProject.Models;
using MySql.Data.MySqlClient;
using System.Configuration;

namespace DatabaseProject.Controllers
{
    public class ContentItemController : Controller
    {

        //
        // GET: /ContentItem/
        [Authorize]
        public ActionResult Index(int page = 0)
        {
            Session["currentPage"] = page;
            PostListModel post_list = new PostListModel();
            if (Session["searchTopic"] != null)
            {
                //IncludeSearchedPosts(ref post_list, page);
                QueryController queryCommand = new QueryController();
                post_list = queryCommand.get_posts((int)HttpContext.Session["userSessionID"], false, 1, page, (string)Session["searchTopic"]);
                Session["totalPages"] = (int)Math.Ceiling((double)post_list.total_posts/(double)5);
                Session["isSearchedPosts"] = true; //used to preserve the number of pages that correlate to searched or regular posts
            }
            else
            {
                QueryController queryCommand = new QueryController();
                post_list = queryCommand.get_posts((int)HttpContext.Session["userSessionID"], false, 1, page);
                if (Session["isSearchedPosts"] == null) Session["isSearchedPosts"] = false; //For initialization purposes
                if (Session["totalPages"] == null || !(bool)Session["isSearchedPosts"])
                {
                    Session["totalPages"] = (int)Math.Ceiling((double)post_list.total_posts / (double)5); // Get the number of pages needed for pagination in the Content/Read page
                    Session["isSearchPosts"] = false;
                    Session["searchTopic"] = ""; // Resetting search topic
                }
            }
            return View(post_list);
        }
        
        //
        // POST: /ContentItem/
        [HttpPost]
        public ActionResult Index(int id, PostListModel postList) // This is for user input on the rating, NOT on page changing
        {                                                         // If page parameter, URL may not know which to go to and throw an error
            QueryController queryCommand = new QueryController();
            queryCommand.rate_post((int)HttpContext.Session["userSessionID"], id, postList.rating.rate); // id is in reference to the CID (post ID)
            //PostListModel post_list = queryCommand.get_posts((int)HttpContext.Session["userSessionID"]);
            //return View(post_list);
            return RedirectToAction("Index");
        }

        //
        // GET: /ContentItem/Write
        public ActionResult Write()
        {
            NewPost_UI_Data post_data = new NewPost_UI_Data { new_post = new NewPostModel(), friendships = new List<string>() };
            QueryController queryCommand = new QueryController();
            post_data.friendships = queryCommand.get_friendship((int)HttpContext.Session["userSessionID"]);
            return View(post_data);
        }
        
        //
        // POST: /ContentItem/Write
        [HttpPost]
        public ActionResult Write(NewPost_UI_Data post_data)
        {
            QueryController queryCommand = new QueryController();
            post_data.new_post.pid = (int)HttpContext.Session["userSessionID"]; 
            queryCommand.new_post(post_data.new_post);
            return RedirectToAction("Index");
        }

        //
        // GET: /ContentItem/Search
        public ActionResult Search()
        {
            return View();
        }

        //
        // POST: /ContentItem/Search/topic
        [HttpPost]
        public ActionResult Search(SearchModel topic)
        {
            try
            {
                if (topic.searchTopic == null) // User doesn't provide any text input
                {
                    return View();
                }

                if (topic.searchTopic != "all") // "all" will reset to default post types
                {
                    //QueryController queryCommand = new QueryController();
                    //PostListModel post_list = queryCommand.get_posts((int)HttpContext.Session["userSessionID"], false, 1, 0, topic.searchTopic);
                    Session["searchTopic"] = topic.searchTopic;
                    //Session["searchedPosts"] = post_list;
                    return RedirectToAction("Index");
                }
                else
                {

                    //Session["searchedPosts"] = null; // if "all": clear for future searches
                    Session["searchTopic"] = null;
                    Session["totalPages"] = null;
                    return RedirectToAction("Index");
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

DatabaseProject/Views/Shared/_ContentLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Content Home Page";
}

<div class="row">
    <div class="span2">
        <div class="tabbable tabs-left pull-left">
            <ul class="nav nav-tabs">
                <li>
                    <a href="@Url.Action("Index", "ContentItem", new { page = 0})" data-toggle="body"><i class="icon-book"></i>Read</a>
                </li>
                <li>
                    <a href="@Url.Action("Write","ContentItem")" data-toggle="body"><i class="icon-pencil"></i>Write</a>
                 </li>
                <li>
                    <a href="@Url.Action("Search", "ContentItem")" data-toggle"body"><i class="icon-search"></i>Search</a>
                </li>
            </ul>
        </div> @*--End tabbable*@
    </div>@*--End span2*@
    <div class="span7">
        <div class="body pull-left">
            @RenderBody()
        </div> @*--End body*@
    </div> @*--End span6*@
</div>@*--End row*@

DatabaseProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

        <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/bootstrap/css/bootstrap-responsive.min.css")" rel="stylesheet" type="text/css" /> 
    </head>
    <body>
        <header>
            <div class="row">
                <div class="span12">
                    <p class="site-title">@Html.ActionLink("CS308 DATABASE PROJECT", "Index", "Home")</p>
                    <div class="row">
                        <div class="span8">
                            <div class="navbar">
                                <div class="navbar-inner">
                                    <div class="container-fluid">
                                        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                            <i class="icon-align-justify icon-white"></i>
                                        </a>
                                        <a class="brand" href="http://www.poly.edu">NYU-Poly</a>
                                        <div class="nav-collapse">
                                            <ul class="nav">
                                                <li class="divider-vertical"></li>
                                                <li class="@(ViewBag.Active == "Home" ? "active" : "")">
                                                    <a href="@Url.Action("Index","Home")">
                                                        <i class="icon-home icon-white"></i>
                                                        Home
                                                    </a>
                                                </li>
                                                <li class="divider-vertical"></li>
                                                <li class="@(ViewBag.Active == "Public Posts" ? "active" : "")">
                                                    <a href="@Url.Action("PublicPosts","Home")">
                                                        <i class="icon-globe icon-white"></i>
                                                        Public Posts
                                                    </a>
                                                </li>
                                                <li class="divider-vertical"></li>
                                                <li class="@(ViewBag.Active == "Contact" ? "active" : "")">
                                                    <a href="@Url.Action("Contact","Home")">
                                                        <i class="icon-envelope icon-white"></i>
                                                        Contact
                                                    </a>
                                                </li>
                                                <li class="divider-vertical"></li>
                                                <li class="@(ViewBag.Active == "Content" ? "active" : "")">
                                                    <a href="@Url.Action("Index","ContentItem")">
                                                        <i class="icon-comment icon-white"></i>
                                                        Content
                                                    </a>
                                                </li>
                                                <li class="divider-vertical"></li>
                                                <li class="@(ViewBag.Active == "Privacy" ? "active" : "")">
                                                    <a href="@Url.Action("Index","Privacy")">
                                                        <i class="icon-lock icon-white"></i>
                                                        Privacy
                                                    </a>
                                                </li>                                            
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="span4"> @*Looks good on a screen smaller than 1920x1080*@
                            <section id="login">
                                @Html.Partial("_LoginPartial")
                            </section>
                        </div>
                    </div>
                 </div>
            </div>
                
        </header>
        <div id="body"> @*THIS IS WHERE OUR WEBSITE WILL BE SHOWN FROM*@
            @RenderSection("featured", required: false)
            <section class="content-wrapper clear-fix"> @*removed 'main-content' because it's not in good taste*@
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="row">
                <div class="span4"> @*Adjust the span according to how long the text below will be*@
                    <p>&copy; @DateTime.Now.Year - Polytechnic Institute of NYU - Introduction to Databases</p>
                </div>
            </div>
            <!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style ">
                <a class="addthis_button_preferred_1"></a>
                <a class="addthis_button_preferred_2"></a>
                <a class="addthis_button_preferred_3"></a>
                <a class="addthis_button_preferred_4"></a>
                <a class="addthis_button_compact"></a>
                <a class="addthis_counter addthis_bubble_style"></a>
            </div>
            <!-- AddThis Button END -->
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)

        <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/bootstrap/bootstrap.min.js")" type="text/javascript"></script>

        <script type="text/javascript">var addthis_config = { "data_track_addressbar": true };</script>
        <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-50c58984722b5578"></script>
    </body>
</html>

DatabaseProject/Views/Shared/_PrivacyLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Content Home Page";
}

<div class="row">
    <div class="span2">
        <div class="tabbable tabs-left pull-left">
            <ul class="nav nav-tabs">
                <li>
                    <a href="@Url.Action("Index", "Privacy")" data-toggle="body"><i class="icon-user"></i>View Groups</a>
                </li>
                <li>
                    <a href="@Url.Action("AddGroup", "Privacy")" data-toggle="body"><i class="icon-plus-sign"></i>Add Group</a>
                </li>
                <li>
                    <a href="@Url.Action("RemoveGroup", "Privacy")" data-toggle="body"><i class="icon-minus-sign"></i>Remove Group</a>
                </li>
                <li>
                    <a href="@Url.Action("Add","Privacy")" data-toggle="body"><i class="icon-plus-sign"></i>Add User</a>
                 </li>
                <li>
                    <a href="@Url.Action("Remove","Privacy")" data-toggle="body"><i class="icon-minus-sign"></i>Remove User</a>
                </li>
            </ul>
        </div> @*--End tabbable*@
    </div>@*--End span2*@
    <div class="span7">
        <div class="body pull-left">
            @RenderBody()
        </div> @*--End body*@
    </div> @*--End span6*@
</div>@*--End row*@