DatabaseProject/Controllers/PrivacyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DatabaseProject.Models;

namespace DatabaseProject.Controllers
{
    public class PrivacyController : Controller
    {
        //
        // GET: /Privacy/
        [Authorize]
        public ActionResult Index()
        {
            PrivacyModel group_data = new PrivacyModel { groups = new List<string>() };
            QueryController queryCommand = new QueryController();
            group_data.groups = queryCommand.get_friendship((int)HttpContext.Session["userSessionID"]);
            return View(group_data);
        }

        //
        // Post: /Privacy/ViewGroupUsers
        [Authorize]
        [HttpPost]
        public ActionResult ViewGroupUsers(PrivacyModel privacyModel)
        {
            privacyModel.users = new List<KeyValuePair<int, KeyValuePair<string, string>>>();
            QueryController queryCommand = new QueryController();
            privacyModel.users = queryCommand.get_users((int)HttpContext.Session["userSessionID"], privacyModel.group);
            return View(privacyModel);
        }

        //
        // GET: /Privacy/Add
        public ActionResult Add()
        {
            PrivacyModel group_data = new PrivacyModel { groups = new List<string>() };
            QueryController queryCommand = new QueryController();
            group_data.groups = queryCommand.get_friendship((int)HttpContext.Session["userSessionID"]);
            return View(group_data);
        }

        //
        // POST: /Privacy/AddToGroup
        [HttpPost]
        public ActionResult AddToGroup(PrivacyModel privacyModel)
        {
            privacyModel.users = new List<KeyValuePair<int, KeyValuePair<string, string>>>();
            HttpContext.Session["userGroup"] = privacyModel.group;
            QueryController queryCommand = new QueryController();
            privacyModel.users = queryCommand.get_other_users((int)HttpContext.Session["userSessionID"], privacyModel.group);
            return View(privacyModel);
        }

        //
        // POST: /Privacy/AddUserToGroup
        [HttpPost]
        public ActionResult AddUserToGroup(PrivacyModel privacyModel)
        {
            QueryController queryCommand = new QueryController();
            queryCommand.add_to_group((int)HttpContext.Session["userSessionID"], privacyModel.user, (string)HttpContext.Session["userGroup"]);
            return RedirectToAction("Index");
        }
        //
        // GET: /Privacy/Remove/
        public ActionResult Remove()
        {
            PrivacyModel group_data = new PrivacyModel { groups = new List<string>() };
            QueryController queryCommand = new QueryController();
            group_data.groups = queryCommand.get_friendship((int)HttpContext.Session["userSessionID"]);
            return View(group_data);
        }

        //
        // POST: /Privacy/RemoveUser
        [HttpPost]
        public ActionResult RemoveUser(PrivacyModel privacyModel)
        {
            privacyModel.users = new List<KeyValuePair<int, KeyValuePair<string, string>>>();
            HttpContext.Session["userGroup"] = privacyModel.group;
            QueryController queryCommand = new QueryController();
            privacyModel.users = queryCommand.get_users((int)HttpContext.Session["userSessionID"], privacyModel.group);
            return View(privacyModel);
        }

        [HttpPost]
        public ActionResult RemoveUserFromGroup(PrivacyModel privacyModel)
        {
            QueryController queryCommand = new QueryController();
            queryCommand.remove_from_group((int)HttpContext.Session["userSessionID"], privacyModel.user, (string)HttpContext.Session["userGroup"]);
            return RedirectToAction("Index");
        }

        //
        // GET: /Privacy/AddGroup
        [Authorize]
        public ActionResult AddGroup()
        {
            return View();
        }

        //
        // POST: /Privacy/AddNewGroup
        [HttpPost]
        public ActionResult AddNewGroup(PrivacyModel privacyModel)
        {
            QueryController queryCommand = new QueryController();
            queryCommand.add_group((int)HttpContext.Session["userSessionID"], privacyModel.group);
            return RedirectToAction("Index");
        }

        //
        // GET: /Privacy/RemoveGroup
        [Authorize]
        public ActionResult RemoveGroup()
        {
            PrivacyModel group_data = new PrivacyModel { groups = new List<string>() };
            QueryController queryCommand = new QueryController();
            group_data.groups = queryCommand.get_friendship((int)HttpContext.Session["userSessionID"]);
            return View(group_data);
        }

        //
        // POST: /Privacy/RemoveUserGroup
        [HttpPost]
        public ActionResult RemoveUserGroup(PrivacyModel privacyModel)
        {
            QueryController queryCommand = new QueryController();
            queryCommand.remove_group((int)HttpContext.Session["userSessionID"], privacyModel.group);
            return RedirectToAction("Index");
        }
    }
}

DatabaseProject/Views/Privacy/Add.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}

@{
    List<SelectListItem> group_lst = new List<SelectListItem>();

    foreach (var x in Model.groups)
    {
        group_lst.Add(new SelectListItem() { Text = x, Value = x, Selected = false });   
    }

    SelectList groups = new SelectList(group_lst, "Value", "Text");
}

<h3>Please select a group to add to</h3>
@using(Html.BeginForm("AddToGroup","Privacy"))
{
    <fiedset>
        <div class="input-append">
            @Html.DropDownListFor(m => m.group, groups)
            <button class="btn" type="submit"><i class="icon-search"></i></button>
        </div>
    </fiedset>
}

DatabaseProject/Views/Privacy/AddGroup.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "AddGroup";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}

<h3>Please enter in the name of a new group</h3>
@using(Html.BeginForm("AddNewGroup","Privacy"))
{
    <fiedset>
        <div class="input-append">
            @Html.TextBoxFor(m => m.group)
            <button class="btn" type="submit"><i class="icon-plus"></i>Add group</button>
        </div>
    </fiedset>
}

DatabaseProject/Views/Privacy/AddtoGroup.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "AddtoGroup";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}

@{
    List<SelectListItem> user_lst = new List<SelectListItem>();

    foreach (var x in Model.users)
    {
        user_lst.Add(new SelectListItem() { Text = (x.Value.Key + ", " + x.Value.Value), Value = x.Key.ToString(), Selected = false });   
    }

    SelectList users = new SelectList(user_lst, "Value", "Text");
}

<h3>Please choose which user to add</h3>
@using(Html.BeginForm("AddUserToGroup","Privacy"))
{
    <fiedset>
        <div class="input-append">
            @Html.DropDownListFor(m => m.user, users)          
            <button class="btn" type="submit"><i class="icon-plus"></i>Add</button>
        </div>
    </fiedset>
}

DatabaseProject/Views/Privacy/Index.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}

@{
    List<SelectListItem> group_lst = new List<SelectListItem>();

    foreach (var x in Model.groups)
    {
        group_lst.Add(new SelectListItem() { Text = x, Value = x, Selected = false });   
    }

    SelectList groups = new SelectList(group_lst, "Value", "Text");
}

<h3>Your Groups</h3>
@using(Html.BeginForm("ViewGroupUsers","Privacy"))
{
    <fiedset>
        <div class="input-append">
            @Html.DropDownListFor(m => m.group, groups)
            <button class="btn" type="submit"><i class="icon-search"></i></button>
        </div>
    </fiedset>
}

DatabaseProject/Views/Privacy/Remove.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "Remove";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}
@{
    List<SelectListItem> group_lst = new List<SelectListItem>();

    foreach (var x in Model.groups)
    {
        group_lst.Add(new SelectListItem() { Text = x, Value = x, Selected = false });   
    }

    SelectList groups = new SelectList(group_lst, "Value", "Text");
}


<h3>Please choose which group to remove from</h3>
@using(Html.BeginForm("RemoveUser","Privacy"))
{
    <fiedset>
        <div class="input-append">
            @Html.DropDownListFor(m => m.group, groups)
            <button class="btn" type="submit"><i class="icon-search"></i></button>
        </div>
    </fiedset>
}

DatabaseProject/Views/Privacy/RemoveGroup.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "RemoveGroup";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}

@{
    List<SelectListItem> group_lst = new List<SelectListItem>();

    foreach (var x in Model.groups)
    {
        group_lst.Add(new SelectListItem() { Text = x, Value = x, Selected = false });   
    }

    SelectList groups = new SelectList(group_lst, "Value", "Text");
}

<h3>Please select a group to remove</h3>
@using(Html.BeginForm("RemoveUserGroup","Privacy"))
{
    <fiedset>
        <div class="input-append">
            @Html.DropDownListFor(m => m.group, groups)
            <button class="btn" type="submit"><i class="icon-minus"></i>Remove group</button>
        </div>
    </fiedset>
}

DatabaseProject/Views/Privacy/RemoveUser.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "RemoveUser";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}

@{
    List<SelectListItem> user_lst = new List<SelectListItem>();

    foreach (var x in Model.users)
    {
        user_lst.Add(new SelectListItem() { Text = (x.Value.Key + ", " + x.Value.Value), Value = x.Key.ToString(), Selected = false });   
    }

    SelectList users = new SelectList(user_lst, "Value", "Text");
}

<h3>Please select which user to remove</h3>
@using(Html.BeginForm("RemoveUserFromGroup","Privacy"))
{
    <fiedset>
        <div class="input-append">
            @Html.DropDownListFor(m => m.user, users)           
            <button class="btn" type="submit"><i class="icon-minus"></i>Remove</button>
        </div>
    </fiedset>
}

DatabaseProject/Views/Privacy/ViewGroupUsers.cshtml
@model DatabaseProject.Models.PrivacyModel

@{
    ViewBag.Title = "View Group Users";
    Layout = "~/Views/Shared/_PrivacyLayout.cshtml";
}

<h2>Your Group's Users</h2>
<ul>
    @foreach(var x in Model.users)
    {
        <li>@x.Value.Key
        ,
        @x.Value.Value</li>
    }
</ul>